apiVersion: v1
kind: Service
metadata:
  name: roadmap-frontend
  namespace: roadmap
spec:
  selector:
    app: roadmap-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
